[placeholders.license]
type = "string"
prompt = "What license would you like?"
default = "MIT"

[placeholders.author]
type = "string"
prompt = "Who is the author of this project?"
default = "Unknown <unknown@unknown.com>"
